### ISSUE TITLE
Panic when network is unreachable

### ISSUE THREAD

**Issue by minus7** [ndecker/fritzbox_exporter#1]
Would be nice to handle this without aborting the program. Happened after a reboot with the systemd service starting before the network was up. DNS resolution worked because it was done on the local box.
```
panic: Get http://fritz.box:49000/igddesc.xml: dial tcp 192.168.0.1:49000: connect: network is unreachable
goroutine 1 [running]:
panic(0x852280, 0xc8201108a0)
        /usr/lib/go/src/runtime/panic.go:481 +0x3e6
main.main()
        .../src/src/github.com/ndecker/fritzbox_exporter/main.go:250 +0xbf
```
Thanks for creating this by the way, it's a nice source of data for my Grafana dashboard (using it for used bandwidth, available DSL bandwidth & uptime)

**Comment by ndecker** [comment]
Now it will retry every minute until the services can be loaded. I am using Promethes + Grafana too.

**Comment by minus7** [comment]
Thanks :)

**Comment by minus7** [comment]
Unfortunately I can't build it anymore (using the package from ArchLinux AUR). Seems like Prometheus' library API changed:
```
../src/github.com/ndecker/fritzbox_exporter/main.go:327: undefined: prometheus.EnableCollectChecks
```

**Comment by ndecker** [comment]
Ok. EnableCollectChecks was removed in prometheus client cf7e1caf172f010a484ddf0bf5052222815b0124. Try again ;-)

**Comment by minus7** [comment]
Works, thanks :)
