### ISSUE TITLE
Chances to get the PRs merged?

### ISSUE THREAD

**Issue by tklein** [ndecker/fritzbox_exporter#13]
Hi,

found this project today and noticed that there are some interesting PRs pending and some other forks ongoing...

Hence the question if the PRs will be merged or if this fork is sort of abandoned?

TIA

/tklein

**Comment by mxschmitt** [comment]
Hi @tklein @foosinn, @iwittkau,

I've created a fork of this repository in which I merged the opened pull requests. Feel free to contribute there, I will be actively maintain this repository:

https://github.com/mxschmitt/fritzbox_exporter

Best regards

Max
