### ISSUE TITLE
Creating a Fork, reviving the project.

### ISSUE THREAD

**Issue by dragetd** [ndecker/fritzbox_exporter#18]
Hello everyone,

reading through the state of this repository, it seems like the author has moved on. Which is completely fine! I have much appreciation and would like to thank @ndecker a lot for the awesome project he has created!

I have not really found that many alternatives to this project. There are some projects like https://github.com/wbwue/FritzExporter by @wbwue or https://github.com/pdreker/fritzbox_exporter by @pdreker , which are worth exploring and contacting.

My go experience is only average, but I have several ideas on how to push this project forward. I would like to start by creating a fork and eventually finding a few co-maintainer. They should be OK with the PR-based workflow and have at least some existing FOSS-Contribution history, then I am happy to add them as maintainer to the fork.
The goal would be to get things into shape with fixes tests, moving from vendoring to go modules.

Then collect issues and existing PRs and throw everything into the coming Hacktoberfest and hack on it.

With this issue I want to call out of anyone interested in helping or maybe there is already such an ongoing effort I have overlooked!

Happy to hear from anyone.

I'll do the next steps hopefully by the weekend.

**Comment by pdreker** [comment]
Hi,

I'm the author of  https://github.com/pdreker/fritzbox_exporter. I'd like to point out that my repo has been forked by @SeaLife, who has made some improvements to the Docker deployment and added support for more Fritz!Box Routers and also seems to be active in developing the code here https://github.com/SeaLife/fritzbox_exporter

To me it seems, that SeaLife's code may be a better starting base, as I would not have gone through the effort of actually writing this in Python, if this had done the trick for me, but to be honest: I don't remember the actual reason. Just the fact that I have this repo in my tracking tells me, that I at least tried to run it and the fact that I still rewrote it tells me that I didn't really get it to work... YMMV ;-)

Also be aware that a project like this will attract a *very* limited audience: People who run Prometheus **and** have a Fritz!Box Router. Who does that, aside from some borderline hardcore nerds... ;-)

That said: if you manage to get a project running, which keeps going, count me in - at least as a user. My Go proficiency is "beginner" if I'm being generous, but that has not stopped me in the past. :-D

**Comment by dragetd** [comment]
That is awesome to hear. Thank you for the info/hint, I will take a look! And yes, I know how niche that is. ;-P

But here in Germany, the price-to-performance ratio for cable modems is really good for AVM products. At least I think so. If you have suggestions for other products, I am happy to hear. :P My Wifi is done by ubiquity anyways.

I just started to monitor my whole network and thought some FritzBox stats in my Grafana would be nice!

And it sounds like a nice Hacktoberfest project! :D

**Comment by pdreker** [comment]
Hi,

I have just followed you to keep in touch should you fork the project or start something new in this area.

Best regards back to my old hometown (Hagen), right next to Dortmund ;-)

**Comment by bachp** [comment]
I'm one of the maintainers of the [fritzbox-exporter](https://github.com/NixOS/nixpkgs-channels/blob/nixos-unstable/pkgs/servers/monitoring/prometheus/fritzbox-exporter.nix) package in [NixOS](https://nixos.org/).

There we currently package for from https://github.com/mxschmitt/fritzbox_exporter which was more up to date, but I think he is also looking for additional maintainers. So I think this might be a good place to start.

**Comment by SeaLife** [comment]
Hey,

im obviously the maintainer of https://github.com/SeaLife/fritzbox_exporter (which is mirrored here: https://git.r3ktm8.de/SeaLife-Docker/fritzbox_exporter/) with ready-to-use docker images for armv7/armv8/amd64. (here: https://hub.docker.com/repository/docker/sealife/fritzbox-exporter)

I recently added metrics for ATA Internet (FTTH connection).

**Comment by dragetd** [comment]
Uh, nice! I did not expect so many 'active' people! Then it would be stupid of me to start another fork! xD

I'll dig into the projects and see where I can do something helpful. I want at least Cable stats for my 6430/6490 :-D

But I am not sure how good my Python-Fu is. I like the 'single binary' deployments of Go (even simpler and slimmer than container), packaging things for Python is difficult for me. =/

Thank you all for the feedback. I'll see where I can dig into. Maybe we can consolidate things a little. :)

**Comment by dragetd** [comment]
It would be nice to have at least a note in the README about the other active projects. But I think @ndecker will not come back to merge such a PR anyways. So I am closing this here and will dig into the other projects. Thank you very much and happy Hacktoberfest!
